### ISSUE TITLE
Hi, can this run on centos5.6 platform?

### ISSUE THREAD

**Issue by nottellyou** [deadbranch/nginx-instaban#1]
Hi, can this run on centos5.6 platform?

**Comment by igor-nikolaychuk** [comment]
Hello, the only specific thing you need from the OS is iptables support. You can check it out by executing 
`sudo iptables -A INPUT -s 127.0.0.1 -p tcp --destination-port 80 -j DROP`.
Now if you can't connect to nginx local server, you can use the utility.
To remove the blocking rule, execute the command:
`sudo iptables -D INPUT -s 127.0.0.1 -p tcp --destination-port 80 -j DROP`
Now you should be able to access your server again. Good luck!

**Comment by nottellyou** [comment]
Hello,  @deadbranch  
Can you compare the nginx-instaban with ddos-deflate V2.6 ？？

**Comment by igor-nikolaychuk** [comment]
Of course! ddos-deflate offers more general ddos protection - it blocks IP addresses with over a pre-configured number of connections. My solution designed for nginx server. It reads nginx error log which contains information about blocked by [limit_req](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html) nginx module ip addresses. You should specify the blocking rule in the nginx configure file(/etc/nginx/nignx.conf by default). 
To limit the the number of connections per ip use [limit_conn](http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html) module.

**Comment by igor-nikolaychuk** [comment]
I've just added nginx configuration example with connection and request per ip limitation.

**Comment by nottellyou** [comment]
Great, I will try  it in my VPS .
